# frontend/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
# Cài đặt toàn bộ dependencies
RUN npm install

COPY . .

# Vite mặc định chạy ở port 5173
EXPOSE 3000

# Thêm tham số --port 3000 để ép Vite chạy đúng port
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]