version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: synergia_postgres_dev
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  backend:
    build: ../../backend
    container_name: synergia_backend_dev
    env_file:
      - .env.dev
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ../../backend:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ../../frontend
    container_name: synergia_frontend_dev
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
      

  minio:
    image: minio/minio:latest
    container_name: synergia_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_dev_data:
  minio_data: