"""add extraction run and latest extraction run

Revision ID: 0117d49f2a14
Revises: 8f3a2b1c9d4e
Create Date: 2026-04-01 12:57:04.813527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0117d49f2a14'
down_revision: Union[str, Sequence[str], None] = '8f3a2b1c9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_documents', sa.Column('latest_extraction_run_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'canonical_documents', 'extraction_runs', ['latest_extraction_run_id'], ['id'])
    op.add_column('extraction_runs', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('extraction_runs', sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extraction_runs', sa.Column('is_from_cache', sa.Boolean(), nullable=True))
    op.add_column('extraction_runs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_runs', 'updated_at')
    op.drop_column('extraction_runs', 'is_from_cache')
    op.drop_column('extraction_runs', 'result_json')
    op.drop_column('extraction_runs', 'provider')
    op.drop_constraint(None, 'canonical_documents', type_='foreignkey')
    op.drop_column('canonical_documents', 'latest_extraction_run_id')
    # ### end Alembic commands ###
