"""add page text json and markdown path to paper record

Revision ID: 5608e9d7ae47
Revises: eb6b73cc1f53
Create Date: 2026-04-14 16:59:28.088730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5608e9d7ae47'
down_revision: Union[str, Sequence[str], None] = 'eb6b73cc1f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_records', sa.Column('docling_markdown_storage_path', sa.Text(), nullable=True))
    op.add_column('paper_records', sa.Column('page_text_json_storage_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_records', 'page_text_json_storage_path')
    op.drop_column('paper_records', 'docling_markdown_storage_path')
    # ### end Alembic commands ###
