"""week3 pipeline schema update

Revision ID: 67850aad9ba8
Revises: 4c41d6619050
Create Date: 2026-03-16 13:52:20.743120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67850aad9ba8'
down_revision: Union[str, Sequence[str], None] = '4c41d6619050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canonical_documents', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('paper_records', sa.Column('duplicate_of_paper_id', sa.UUID(), nullable=True))
    op.add_column('paper_records', sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('paper_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default='uploaded',
               existing_nullable=False)
    op.create_index(op.f('ix_paper_records_duplicate_of_paper_id'), 'paper_records', ['duplicate_of_paper_id'], unique=False)
    op.create_foreign_key(None, 'paper_records', 'paper_records', ['duplicate_of_paper_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paper_records', type_='foreignkey')
    op.drop_index(op.f('ix_paper_records_duplicate_of_paper_id'), table_name='paper_records')
    op.alter_column('paper_records', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('paper_records', 'is_duplicate')
    op.drop_column('paper_records', 'duplicate_of_paper_id')
    op.alter_column('canonical_documents', 'fingerprint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
