"""create core tables

Revision ID: a1f93ee01cc3
Revises: 
Create Date: 2026-03-10 13:24:01.801493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1f93ee01cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('canonical_type', sa.String(length=20), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('title_candidate', sa.Text(), nullable=True),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('ss_paper_id', sa.String(length=255), nullable=True),
    sa.Column('ss_match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metadata_source', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('authors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('extraction_cache_status', sa.String(length=30), server_default='empty', nullable=False),
    sa.Column('match_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_canonical_documents_canonical_key'), 'canonical_documents', ['canonical_key'], unique=True)
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='running', nullable=False),
    sa.Column('problem_statement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('main_method', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_setup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_canonical_document_id'), 'extraction_runs', ['canonical_document_id'], unique=False)
    op.create_table('paper_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('upload_source', sa.String(length=30), server_default='portal', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('extracted_text_preview', sa.Text(), nullable=True),
    sa.Column('detected_doi', sa.String(length=255), nullable=True),
    sa.Column('detected_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_records_canonical_document_id'), 'paper_records', ['canonical_document_id'], unique=False)
    op.create_table('publish_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_record_id', sa.UUID(), nullable=False),
    sa.Column('source_extraction_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('title_override', sa.Text(), nullable=True),
    sa.Column('abstract_override', sa.Text(), nullable=True),
    sa.Column('venue_override', sa.Text(), nullable=True),
    sa.Column('year_override', sa.Integer(), nullable=True),
    sa.Column('authors_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problem_statement_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('main_method_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributions_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_setup_final', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('published_by', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_notified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_record_id'], ['paper_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_extraction_id'], ['extraction_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_versions_paper_record_id'), 'publish_versions', ['paper_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_versions_paper_record_id'), table_name='publish_versions')
    op.drop_table('publish_versions')
    op.drop_index(op.f('ix_paper_records_canonical_document_id'), table_name='paper_records')
    op.drop_table('paper_records')
    op.drop_index(op.f('ix_extraction_runs_canonical_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_canonical_documents_canonical_key'), table_name='canonical_documents')
    op.drop_table('canonical_documents')
    # ### end Alembic commands ###
