"""refactor paper_record status field

Revision ID: d63e55a1e089
Revises: 0117d49f2a14
Create Date: 2026-04-02 12:05:09.552210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63e55a1e089'
down_revision: Union[str, Sequence[str], None] = '0117d49f2a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_records', sa.Column('processing_status', sa.String(length=30), server_default='pending', nullable=False))
    op.add_column('paper_records', sa.Column('processing_stage', sa.String(length=30), nullable=True))
    op.add_column('paper_records', sa.Column('publication_status', sa.String(length=30), server_default='draft', nullable=False))
    op.add_column('paper_records', sa.Column('processing_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_paper_records_processing_stage'), 'paper_records', ['processing_stage'], unique=False)
    op.create_index(op.f('ix_paper_records_processing_status'), 'paper_records', ['processing_status'], unique=False)
    op.create_index(op.f('ix_paper_records_publication_status'), 'paper_records', ['publication_status'], unique=False)
    op.drop_column('paper_records', 'parse_error')
    op.drop_column('paper_records', 'status')
    op.drop_column('paper_records', 'parse_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_records', sa.Column('parse_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('paper_records', sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'uploaded'::character varying"), autoincrement=False, nullable=False))
    op.add_column('paper_records', sa.Column('parse_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_paper_records_publication_status'), table_name='paper_records')
    op.drop_index(op.f('ix_paper_records_processing_status'), table_name='paper_records')
    op.drop_index(op.f('ix_paper_records_processing_stage'), table_name='paper_records')
    op.drop_column('paper_records', 'processing_error')
    op.drop_column('paper_records', 'publication_status')
    op.drop_column('paper_records', 'processing_stage')
    op.drop_column('paper_records', 'processing_status')
    # ### end Alembic commands ###
