"""fix chunks

Revision ID: d95e0b7ed581
Revises: e14ad7b112e3
Create Date: 2026-04-23 09:06:04.963437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95e0b7ed581'
down_revision: Union[str, Sequence[str], None] = 'e14ad7b112e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('section_type', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('section_heading_level', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('section_full_path', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('is_retrievable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'is_retrievable')
    op.drop_column('document_chunks', 'section_full_path')
    op.drop_column('document_chunks', 'section_heading_level')
    op.drop_column('document_chunks', 'section_type')
    # ### end Alembic commands ###
