"""addsection level to document_section

Revision ID: e14ad7b112e3
Revises: 8c848805c00f
Create Date: 2026-04-23 08:33:43.225908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14ad7b112e3'
down_revision: Union[str, Sequence[str], None] = '8c848805c00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_sections', sa.Column('heading_number', sa.String(length=50), nullable=True))
    op.add_column('document_sections', sa.Column('heading_level', sa.Integer(), nullable=False))
    op.add_column('document_sections', sa.Column('parent_section_id', sa.UUID(), nullable=True))
    op.add_column('document_sections', sa.Column('full_path', sa.Text(), nullable=True))
    op.create_index(op.f('ix_document_sections_parent_section_id'), 'document_sections', ['parent_section_id'], unique=False)
    op.create_foreign_key(None, 'document_sections', 'document_sections', ['parent_section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_sections', type_='foreignkey')
    op.drop_index(op.f('ix_document_sections_parent_section_id'), table_name='document_sections')
    op.drop_column('document_sections', 'full_path')
    op.drop_column('document_sections', 'parent_section_id')
    op.drop_column('document_sections', 'heading_level')
    op.drop_column('document_sections', 'heading_number')
    # ### end Alembic commands ###
