"""add activity logs table

Revision ID: eb6b73cc1f53
Revises: d156d3edacbe
Create Date: 2026-04-12 17:43:29.539738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb6b73cc1f53'
down_revision: Union[str, Sequence[str], None] = 'd156d3edacbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('paper_record_id', sa.UUID(), nullable=True),
    sa.Column('canonical_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ),
    sa.ForeignKeyConstraint(['paper_record_id'], ['paper_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_canonical_document_id'), 'activity_logs', ['canonical_document_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_object_id'), 'activity_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_paper_record_id'), 'activity_logs', ['paper_record_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_status'), 'activity_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_status'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_paper_record_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_object_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_canonical_document_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
